#!/usr/bin/env python3
"""
Generate V4__seed_cities.sql from GeoNames cities15000.txt dataset.

Downloads cities15000.zip and countryInfo.txt from GeoNames, extracts city data,
maps country codes to country names, and produces multi-row INSERT batches.

Output: services/destination-service/src/main/resources/db/migration/V4__seed_cities.sql
"""

import csv
import io
import os
import sys
import urllib.request
import zipfile

CITIES_URL = "https://download.geonames.org/export/dump/cities15000.zip"
COUNTRY_URL = "https://download.geonames.org/export/dump/countryInfo.txt"
OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "services",
    "destination-service",
    "src",
    "main",
    "resources",
    "db",
    "migration",
    "V4__seed_cities.sql",
)
BATCH_SIZE = 1000


def download_country_map():
    """Download countryInfo.txt and return {code: name} mapping."""
    print("Downloading countryInfo.txt...")
    with urllib.request.urlopen(COUNTRY_URL) as resp:
        content = resp.read().decode("utf-8")

    country_map = {}
    for line in content.splitlines():
        if line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 5:
            code = parts[0]  # ISO2
            name = parts[4]  # Country name
            country_map[code] = name
    return country_map


def download_cities():
    """Download cities15000.zip, extract, and return rows."""
    print("Downloading cities15000.zip...")
    with urllib.request.urlopen(CITIES_URL) as resp:
        zip_data = resp.read()

    with zipfile.ZipFile(io.BytesIO(zip_data)) as zf:
        with zf.open("cities15000.txt") as f:
            content = f.read().decode("utf-8")

    rows = []
    reader = csv.reader(io.StringIO(content), delimiter="\t")
    for parts in reader:
        if len(parts) < 15:
            continue
        geoname_id = parts[0]
        name = parts[1]
        lat = parts[4]
        lng = parts[5]
        country_code = parts[8]
        try:
            population = int(parts[14])
        except (ValueError, IndexError):
            population = 0
        if population >= 15000:
            rows.append((geoname_id, name, country_code, lat, lng, population))
    return rows


def escape_sql(value):
    """Escape single quotes for SQL string literals."""
    return value.replace("'", "''")


def generate_sql(rows, country_map):
    """Generate multi-row INSERT SQL file."""
    print(f"Generating SQL for {len(rows)} cities...")
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("-- GeoNames cities15000 seed data (~{} cities with population >= 15000).\n".format(len(rows)))
        f.write("-- Generated by scripts/generate-seed-sql.py — do not edit manually.\n")
        f.write("-- Source: https://download.geonames.org/export/dump/cities15000.zip\n\n")

        for batch_start in range(0, len(rows), BATCH_SIZE):
            batch = rows[batch_start : batch_start + BATCH_SIZE]
            f.write(
                "INSERT INTO cities (geoname_id, name, country, country_code, lat, lng, population) VALUES\n"
            )
            values = []
            for geoname_id, name, country_code, lat, lng, population in batch:
                country_name = country_map.get(country_code, country_code)
                values.append(
                    f"({geoname_id}, '{escape_sql(name)}', '{escape_sql(country_name)}', '{country_code}', {lat}, {lng}, {population})"
                )
            f.write(",\n".join(values))
            f.write(";\n\n")

    print(f"Written to: {OUTPUT_PATH}")


def main():
    country_map = download_country_map()
    print(f"Loaded {len(country_map)} country codes")
    rows = download_cities()
    print(f"Found {len(rows)} cities with population >= 15000")
    generate_sql(rows, country_map)
    print("Done!")


if __name__ == "__main__":
    main()
